eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /data/**
      service-id: data-interface-service
#增加以下两个配置就好了
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
